package ru.miit.my.cabinet.request.model;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;

import ru.miit.my.frameworkext.EntityImpl;
import ru.miit.my.frameworkext.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 25 13:17:40 MSK 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RequestforummessageViewRowImpl extends ViewRowImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        YesNo {
            public Object get(RequestforummessageViewRowImpl obj) {
                return obj.getYesNo();
            }

            public void put(RequestforummessageViewRowImpl obj, Object value) {
                obj.setYesNo((Boolean)value);
            }
        }
        ,
        isNewRow {
            public Object get(RequestforummessageViewRowImpl obj) {
                return obj.getisNewRow();
            }

            public void put(RequestforummessageViewRowImpl obj, Object value) {
                obj.setisNewRow((Boolean)value);
            }
        }
        ,
        RequestforummessageView {
            public Object get(RequestforummessageViewRowImpl obj) {
                return obj.getRequestforummessageView();
            }

            public void put(RequestforummessageViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(RequestforummessageViewRowImpl object);

        public abstract void put(RequestforummessageViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int YESNO = AttributesEnum.YesNo.index();
    public static final int ISNEWROW = AttributesEnum.isNewRow.index();
    public static final int REQUESTFORUMMESSAGEVIEW = AttributesEnum.RequestforummessageView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RequestforummessageViewRowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute YesNo.
     * @return the YesNo
     */
    public Boolean getYesNo() {
        return (Boolean) getAttributeInternal(YESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute YesNo.
     * @param value value to set the  YesNo
     */
    public void setYesNo(Boolean value) {
        setAttributeInternal(YESNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute isNewRow.
     * @return the isNewRow
     */
    public Boolean getisNewRow() {
        return getEntity(0).getEntityState() == oracle.jbo.server.EntityImpl.STATUS_NEW;//(String) getAttributeInternal(SMTH3);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute isNewRow.
     * @param value value to set the  isNewRow
     */
    public void setisNewRow(Boolean value) {
        setAttributeInternal(ISNEWROW, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link RequestforummessageView.
     */
    public RowIterator getRequestforummessageView() {
        return (RowIterator)getAttributeInternal(REQUESTFORUMMESSAGEVIEW);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
