package ru.miit.my.cabinet.request.model;

import oracle.jbo.server.AttributeDefImpl;

import ru.miit.my.frameworkext.EntityImpl;
import ru.miit.my.frameworkext.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 15 18:21:37 MSK 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Typetest3ViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_TYPETEST3 = 0;
    public static final int ENTITY_EMPLOYEE = 1;

    /**
     * This is the default constructor (do not remove).
     */
    public Typetest3ViewRowImpl() {
    }

    /**
     * Gets Typetest3 entity object.
     * @return the Typetest3
     */
    public EntityImpl getTypetest3() {
        return (EntityImpl)getEntity(ENTITY_TYPETEST3);
    }

    /**
     * Gets Employee entity object.
     * @return the Employee
     */
    public EntityImpl getEmployee() {
        return (EntityImpl)getEntity(ENTITY_EMPLOYEE);
    }
}
